export * from './base.interface';
export * from './jwt-payload.interface';
export * from './pessoa.interface';
export * from './user.interface';
export * from './login-payload.interface';
export * from './signup-payload.interface';
export * from './produto.interface';
export * from './compra.interface';
export * from './item-compra.interface';
